remote_url: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vTKJAloKasy0BWOFNam_9ZXeUgs6T0vgzmdRgBQdFLRcaEVFHE1ew_biVyZymhuakjT3O1Lok27KsUG/pub?output=csv'
proj_dir: 'C:\Users\Spencer\Desktop\FRCCSpring2025\ProgrammingGIS\Labs\Lab1\WestNileOutbreak\'
data_format: 'GSheet'
geocoder_prefix_url: 'https://geocoding.geo.census.gov/geocoder/locations/onelineaddress?address='
geocoder_suffix_url: '&benchmark=2020&format=json'